@echo off
echo Stopping all Node.js processes...
taskkill /F /IM node.exe 2>nul

echo Clearing npm cache...
npm cache clean --force

echo Waiting 3 seconds...
timeout /t 3 /nobreak >nul

echo Starting server...
node server.js